spring:
  application:
    name: Blogging-App
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
